### ISSUE TITLE
KeyError: 'http'

### ISSUE THREAD

**Issue by KaIZeR99-code** [AlexAplin/nndownload#123] opened 2022-03-21 17:51 UTC
![image](https://user-images.githubusercontent.com/83866575/159333828-1625eda5-d377-456a-b62c-beeed4f3af5f.png)
Got an error when I try to download Crush Gear Nitro episode
https://www.nicovideo.jp/watch/so39865442

**Comment by KaIZeR99-code** [comment] 2022-03-21 17:57
I already have the membership for the channel

**Comment by AlexAplin** [comment] 2022-03-25 01:33
Please provide the source of the page (View Source) as an attachment.

**Comment by KaIZeR99-code** [comment] 2022-03-25 01:43
[Source.txt](https://github.com/AlexAplin/nndownload/files/8346708/Source.txt)
Is this the correct one? Sorry I'm still to new to this kind of thing...

**Comment by AlexAplin** [comment] 2022-03-25 01:47
This appears to use HLS as the auth type, and I just noticed it's a so# video. This is a duplicate of #102.

**Closed as completed by AlexAplin** 2022-03-25 01:47 UTC
Labels: duplicate
