### ISSUE TITLE
Getting "ERROR: ConnectionError"

### ISSUE THREAD

**Issue by MonoS** [AlexAplin/nndownload#109] opened 2021-08-19 15:01 UTC
As the title, i get this error when trying to download a video, attached the full log
[[nndownload] 2021-08-18.log](https://github.com/AlexAplin/nndownload/files/7015368/nndownload.2021-08-18.log)

I've tried the same video with a fork of youtube-dl and it worked fine.

**Comment by AlexAplin** [comment] 2021-08-19 15:46
I'm unable to reproduce this. The log suggests an issue resolving the host, which could be because of a proxy or DNS error.

```
python .\nndownload.py -u [...] -p [...] https://www.nicovideo.jp/watch/sm31030077
Logging in...
Logged in.
Performing initial API request...
Performed initial API request.
Downloading sm31030077 to "sm31030077 - 【初音ミク】Happily Ever【オリジナルMV】.mp4"...
|#################        | 69/100 @ 210.42KB /s
```

**Closed as completed** 2021-08-19 15:48 UTC
Labels: invalid

**Comment by MonoS** [comment] 2021-08-19 16:32
Thank you for the clarification, for some reason i'm getting this error using the exe version but not with the python's one, i'll try to diagnose this on my end.
